### ISSUE TITLE
FileDropzone bind:files does not appear to work as expected

### ISSUE THREAD

**Issue by fatstack** [skeletonlabs/skeleton#1021]
### Current Behavior

Since the 0.124.x release we've had issues using bind with the FileDropzone.

Our code seems to be correct, as it works as expected if I switch from using `<FileDropzone ... />` to a regular file input `<input type="file" ... />`

### Steps To Reproduce

1. Set up a regular file type input using bind that works as expected.

e.g.
`<input type="file" name="example" bind:files on:change={changeImage} accept="image/jpeg" />`

2. Import FileDropzone and switch the input to use it instead.

e.g.
`<FileDropzone name="example" bind:files on:change={changeImage} accept="image/jpeg" />`

### Anything else?

Thank you, Skeleton is fantastic ❤️

**Comment by endigo9740** [comment]
Hey @fatstack, hmm have you updated to the new release this week? This was one of the items addressed:
https://github.com/skeletonlabs/skeleton/pull/949

Details on the latest release can be found here:
- https://github.com/skeletonlabs/skeleton/discussions/995

It's a large update with some breaking changes, so take your time, but if you're able to upgrade and this resolves this issue please let us know. Thanks!

**Comment by fatstack** [comment]
Thanks @endigo9740!

Sorry I should have clarified, yes I can confirm that we're using the latest 0.132.5 release. The issue first occurred after upgrading to 0.124.x from 0.99.x and is still an issue for us after upgrading to 0.132.5.

**Comment by endigo9740** [comment]
@fatstack I've managed to recreate the issue here and have implemented a fix. Generally idea is that the File Dropzone doesn't operate as closely to the File Button as I had imagined. The File Button doesn't require explicit binding, while the File Dropzone does.

This fix has been merged into dev branch and will be part of the next release.

**Comment by grandslammer** [comment]
This issue is still occurring in Skeleton 1.0.
"Uncaught TypeError: can't access property 0, files is undefined" upon file upload.

**Comment by grandslammer** [comment]
> 

Yes, see https://discord.com/channels/1003691521280856084/1084785138099048448/1084785138099048448

**Comment by Sarenor** [comment]
Alright, then the linked [PR ](https://github.com/skeletonlabs/skeleton/pull/1147) should fix that :)
