### ISSUE TITLE
Safari on macOS completely butchers Progress Radials

### ISSUE THREAD

**Issue by lia-07** [skeletonlabs/skeleton#1370]
### Current Behavior

Not sure if this is currently a known issue but Progress Radials (linear and indeterminate) get rendered very strangely in Safari on my machine, running macOS `13.3.1`. I have tested in Chrome and there is no issue, AND in Safari on my iPhone, so  it's just Safari being Safari again. I'm not sure if theres anything that can happen on this side of the equation to fix this, but considering Safari has ~20% of the web browser marketshare it might be worth looking into.

https://user-images.githubusercontent.com/107384739/234224204-b501e602-0516-449b-82e6-6e55c57da7e6.mp4

### Reproduction / Steps To Reproduce

You just need to visit the homepage (or [here](https://www.skeleton.dev/components/progress-radials)) in Safari on a Mac.

**Comment by Sarenor** [comment]
We had a similar Safari animation bug at my previous company. Sadly, that was nearly a year ago and I can't remember how we fixed it...

I just remember that it definitely was a case of Safari being Safari.

**Comment by moalamri** [comment]
It looks fine on my end, what iOS version are you using?

![image](https://user-images.githubusercontent.com/964077/234233912-7d4b8e65-46c7-43cf-b72f-d3348aebc0cf.jpeg)

**Comment by endigo9740** [comment]
@lia-07 I'm probably going to need more information for how to reproduce this. I'm running macOS 13.2 and Safari 16.3 and I'm not seeing this issue. I've tried resizing the window.

![Screenshot 2023-04-25 at 10 23 24 AM](https://user-images.githubusercontent.com/1509726/234325821-129a8a08-c6ef-4ff2-be1d-57661fb7e67a.png)

This component has not undergone any notable changes in weeks if not months, so I think someone would have reported this if this was a common issue. Can you provide your Safari version and perhaps try in Incognito to confirm no extensions are affecting the display please.

**Comment by endigo9740** [comment]
Can't replicate, no response. Closing this out.

**Comment by lia-07** [comment]
> Can't replicate, no response. Closing this out.

Sorry! I haven't been on GitHub in a while and I had email notifications off.

I am on Safari version 16.4 (18615.1.26.11.23), and still have the issue in Private windows.

**Comment by endigo9740** [comment]
I'll reopen and plan to update and test again. But if we can't replicate we may not be able to help here. Currently you're the only person to report this issue.

**Comment by endigo9740** [comment]
@lia-07 I've now updated to macOS Ventura 13.3.1, which includes Safari 16.4. This means I should match you, however I'm still unable to replicate the issues you're seeing. 

![Screenshot 2023-05-04 at 3 08 31 PM](https://user-images.githubusercontent.com/1509726/236318009-33c61fcf-f1eb-4677-865c-d69b80fa2b54.png)

I do note a slight wobble on Safari that I don't see on other browsers, like Chrome, but nothing as pronounced as you showed above.

https://user-images.githubusercontent.com/1509726/236318352-f6db5b56-35fc-4108-8bb0-74fbda55e8b5.mp4

I've tried different themes and resizing the window to different sizes. Nothing I'm throwing at this is allowing me to replicate the issue you're seeing. I mentioned above, but you're the first and only user to report this issue, so I hate to say but I worry something may be amiss on your end.

If you can find more specific steps to reproduce, please share and again I'll be happy to reopen this issue. Likewise I'll keep my ear to the ground if anyone else reports a similar issue. But unless I can reproduce, I can't debug or resolve the issue. I hope you understand and sorry we can't do more!

**Comment by lia-07** [comment]
I just created another user account on the same machine and it didn't have this problem at all, so obviously it's a problem on my end. The thing is, even after uninstalling my adblocker, clearing cache, and restarting the computer, the issue persisted. Weird.

Anyway, I'm sorry for wasting your time.

**Comment by endigo9740** [comment]
That is so weird. No problem at all, just sorry to hear that was happening. If you happen to discover a cause let us know. Thanks!
