### ISSUE TITLE
v3 Input Group buttons are not affected by Presets

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2985]
### Current Behavior

When creating an input group, the button styles do not display the Preset classes applied. Note that this is working on the Astro docs, but not in a real world SvelteKit project. Which might imply there's a precedence issue that only occurs during the final build process.

![Screenshot 2024-11-19 at 1 38 42 PM](https://github.com/user-attachments/assets/f4665fce-95ff-49a0-a15a-00784e4ead36)

```html
<form class="mx-auto w-full max-w-md space-y-8">
    <div class="input-group divide-surface-200-800 grid-cols-[auto_1fr_auto] divide-x">
        <div class="input-group-cell">S</div>
        <input type="search" placeholder="Search..." />
        <button class="btn preset-filled">Submit</button>
    </div>
</form>
```

### Expected Behavior

You should be free to style the buttons however you wish.

### Steps To Reproduce

1. Create a new v3 SvelteKit project
2. Copy/paste the [examples from our docs](https://next.skeleton.dev/docs/tailwind/forms#groups)
3. Note the button styles do not match how they are show in the docs

### More Information

Docs: https://next.skeleton.dev/docs/tailwind/forms#groups

**Comment by phamduylong** [comment]
Ran through this a bit, it seems like some of the properties for the preset and `.input-group` in [forms.css](https://github.com/skeletonlabs/skeleton/blob/300204dbbba48555e4054b54a899e8ee3113f07b/packages/skeleton/src/plugin/components/forms.css#L184) are overlapping, and this **"race condition"** is resolved differently in Astro docs and a real world project.

**Comment by endigo9740** [comment]
@phamduylong that was my guess as well. I'm still not entirely happy with how the input groups are handled so leave this one to me. I'll try to revise before launch. Otherwise we might delay this feature to ensure I have proper time to implement breaking changes.

**Comment by endigo9740** [comment]
Resolved by https://github.com/skeletonlabs/skeleton/pull/3189
