### ISSUE TITLE
select form input in RTL mode has overlapping text and down arrow

### ISSUE THREAD

**Issue by tihab** [skeletonlabs/skeleton#3395]
### Current Behavior

In "@skeletonlabs/skeleton": "3.0.0-next.12", the select input is displayed correctly, with proper gaps between the text and the down arrow.
In "@skeletonlabs/skeleton": "3.0.0-next.13" and the official 3.0.0 releases, the text and down arrow are overlapped.

Incorrect behavior in 3.0.0-next.13 and official 3.0.0
<img width="384" alt="Image" src="https://github.com/user-attachments/assets/3aef04b2-6d4e-4e6c-9376-43168313bb00" />

### Expected Behavior

Correct behavior in earlier 3.0.0-next.12
<img width="452" alt="Image" src="https://github.com/user-attachments/assets/b73ba23e-a43e-4ab2-996c-85d9e6d549b0" />

### Link to Reproduction / Stackblitz
https://github.com/tihab/skeleton-demo/

### Environment Information

Tested in browsers: Chrome, Brave, Safari and Edge.

**Comment by phamduylong** [comment]
@tihab can you provide the relevant information on how to reproduce and your browser as well?

**Comment by endigo9740** [comment]
@tihab 

What @phamduylong said, a code snippet and OS/browser at least please.

Also quick question as someone that unfortunately only speaks English and uses LTR. But is this a common occurrence with the native select element? I very intentionally left the default select dropdown arrow icon in place in the hope it might avoid scenarios like this.

Seems maybe we will need to do something to help enforce this though, so I'll research options. Off the top of my head I'd guess a minimum right-hand padding or something along those lines.

**Comment by tihab** [comment]
@phamduylong  Reproduction repo link updated above.

Observations:
The issue is resolved by one of the below actions:
1- using next.12 version
pnpm add -D @skeletonlabs/skeleton@3.0.0-next.12
2- commenting the below line in app.css
# @plugin '@tailwindcss/forms';

**Comment by endigo9740** [comment]
@tihab just FYI [Skeleton v3 has now launched](https://github.com/skeletonlabs/skeleton/discussions/3372), so you should aim to migrate to the stable release. The last launch day release came with a number of style updates and improvements. So we'll need to ensure this issue persists after you update.

**Comment by tihab** [comment]
> [@tihab](https://github.com/tihab) just FYI [Skeleton v3 has now launched](https://github.com/skeletonlabs/skeleton/discussions/3372), so you should aim to migrate to the stable release. The last launch day release came with a number of style updates and improvements, including select elements. So we'll need to ensure this issue persists after you update.

As i mentioned in the issue description above, the problem appeared in next.13 as well as the stable v3 release.

**Comment by endigo9740** [comment]
Ok, just wanted to confirm. If the issue persists on the latest release, then we will aim to review and resolve asap. Thanks.

**Comment by tihab** [comment]
As per my analysis, the issue is caused by the inline padding "**padding-inline: --spacing(3);**" in "packages/skeleton/src/utilities/form-selects.css" which means 0.75rem padding on both ends of the input. This is quite small, hence the overlapping with the text.
